gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - black
    selectedLineBgColor:
      - bold
      - white
    selectedRangeBgColor:
      - white
      - bold
  mouseEvents: false
promptToReturnFromSubprocess: false
# os:
#   edit: 'nvr -cc tabnew --remote {{filename}}'
#   editAtLine: 'nvr -cc tabnew -c :{{line}} --remote {{filename}}'
#   editAtLineAndWait: 'nvr -cc tabnew -c :{{line}} --remote-wait {{filename}}'
#   editInTerminal: false
git:
  pagers:
    - colorArg: always
      pager: delta --light --paging=never
